


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."create_useraccount_after_employee"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    initials TEXT := '';
    word TEXT;
BEGIN
    -- Tách fullName thành các từ và lấy chữ cái đầu
    FOR word IN SELECT unnest(string_to_array(NEW.fullName, ' ')) LOOP
        initials := initials || lower(left(word, 1));
    END LOOP;

    -- Chèn vào UserAccount với password = initials + employeeID
    INSERT INTO UserAccount (userID, password, AccountStatus)
    VALUES (NEW.employeeID, initials || NEW.employeeID::text, 'Unsubmitted');

    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."create_useraccount_after_employee"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."delete_employee_after_account"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  delete from Employee where employeeID = old.userID;
  return old;
end;
$$;


ALTER FUNCTION "public"."delete_employee_after_account"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."gen_employee_id_v2"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    next_suffix int;
BEGIN
    -- Tăng số thứ tự
    UPDATE EmpCounter
    SET lastNumber = lastNumber + 1
    WHERE branchID = NEW.branchID AND roleID = NEW.roleID
    RETURNING lastNumber INTO next_suffix;

    -- Nếu chưa có dòng nào => tạo mới
    IF NOT FOUND THEN
        INSERT INTO EmpCounter (branchID, roleID, lastNumber)
        VALUES (NEW.branchID, NEW.roleID, 0)
        RETURNING lastNumber INTO next_suffix;
    END IF;

    -- Sinh employeeID = ab c def (6 chữ số); def = next_suffix
    NEW.employeeID := NEW.branchID * 10000 + NEW.roleID * 1000 + next_suffix;

    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."gen_employee_id_v2"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."generate_employee_id"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
  declare
    max_id int;
  begin
    select coalesce(max(e.employeeID), 10299) into max_id --bắt đầu từ 10300 là nhân viên giao dịch 
    from Employee e
    where roleID = 3;
    new.employeeID := max_id + 1;
    return new;
  end;
  $$;


ALTER FUNCTION "public"."generate_employee_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."maturity_date_setting"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
declare
  term_months int;
begin
    if new.maturitydate IS NOT NULL then
      -- Ngược lại, lấy termPeriod từ bảng TypeSaving
      select termPeriod into term_months
      from TypeSaving
      where typeID = new.typeID;
  -- Gán giá trị maturityDate = registerTime + termPeriod tháng
      new.maturityDate := new.registerTime + (term_months || ' month')::interval;
    END IF ;
  return new;
end;
$$;


ALTER FUNCTION "public"."maturity_date_setting"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."status_close_closetime"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
    if NEW.status = 'Close' and OLD.status is distinct from NEW.status
    then NEW.CloseTime := NOW();
    
    end if;
  return new; -- trả về bản ghi sau khi chỉnh sửa
end;
$$;


ALTER FUNCTION "public"."status_close_closetime"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."status_open_closetime"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
    if NEW.status = 'Open' and OLD.status is distinct from NEW.status
    then NEW.CloseTime := NULL;
    end if;
  return new; --trả về bản ghi sau chỉnh sửa
end;
$$;


ALTER FUNCTION "public"."status_open_closetime"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."branch" (
    "branchid" integer NOT NULL,
    "branchname" character varying(30)
);


ALTER TABLE "public"."branch" OWNER TO "postgres";


ALTER TABLE "public"."branch" ALTER COLUMN "branchid" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."branch_branchid_seq"
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customer" (
    "customerid" integer NOT NULL,
    "fullname" character varying(70),
    "citizenid" character varying,
    "street" character varying(50),
    "district" character varying(50),
    "province" character varying(50)
);


ALTER TABLE "public"."customer" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."customer_customerid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."customer_customerid_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."customer_customerid_seq" OWNED BY "public"."customer"."customerid";



CREATE SEQUENCE IF NOT EXISTS "public"."emp_suffix_seq"
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    MAXVALUE 99
    CACHE 1;


ALTER SEQUENCE "public"."emp_suffix_seq" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."empcounter" (
    "branchid" integer NOT NULL,
    "roleid" integer NOT NULL,
    "lastnumber" integer DEFAULT 0
);


ALTER TABLE "public"."empcounter" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."employee" (
    "employeeid" integer NOT NULL,
    "fullname" character varying(50),
    "roleid" integer,
    "branchid" integer,
    "email" character varying(30) NOT NULL
);


ALTER TABLE "public"."employee" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."role" (
    "roleid" integer NOT NULL,
    "rolename" character varying(20) NOT NULL,
    CONSTRAINT "role_rolename_check" CHECK ((("rolename")::"text" = ANY (ARRAY[('Teller'::character varying)::"text", ('Accountant'::character varying)::"text", ('Auditor'::character varying)::"text", ('Administrator'::character varying)::"text"])))
);


ALTER TABLE "public"."role" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."role_roleid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."role_roleid_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."role_roleid_seq" OWNED BY "public"."role"."roleid";



CREATE TABLE IF NOT EXISTS "public"."savingbook" (
    "bookid" integer NOT NULL,
    "typeid" integer,
    "customerid" integer,
    "registertime" timestamp without time zone DEFAULT "now"(),
    "maturitydate" timestamp without time zone,
    "status" character varying(10) DEFAULT 'Open'::character varying,
    "closetime" timestamp without time zone,
    "currentbalance" numeric(15,2) DEFAULT 0,
    "openrate" numeric,
    "isactive" boolean DEFAULT true NOT NULL,
    CONSTRAINT "check_currentbalance" CHECK (("currentbalance" >= (0)::numeric)),
    CONSTRAINT "check_maturitydate" CHECK (("maturitydate" >= "registertime")),
    CONSTRAINT "check_registertime" CHECK (("registertime" >= '2025-01-01 00:00:00'::timestamp without time zone)),
    CONSTRAINT "check_status" CHECK ((("status")::"text" = ANY ((ARRAY['Open'::character varying, 'Close'::character varying])::"text"[])))
);


ALTER TABLE "public"."savingbook" OWNER TO "postgres";


COMMENT ON COLUMN "public"."savingbook"."openrate" IS 'Là lãi suất của sổ (lúc mới mở sổ) - sau ngày đáo hạn thì sẽ cập nhật giá trị này đúng với lãi suất hiện tại';



COMMENT ON COLUMN "public"."savingbook"."isactive" IS 'Sổ sẽ được tái tục hay không sau khi đáo hạn ? - trường này chỉ dành khi 1 type saving bị xóa trong khi đó vẫn còn sổ đang hoạt động';



CREATE SEQUENCE IF NOT EXISTS "public"."savingbook_bookid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."savingbook_bookid_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."savingbook_bookid_seq" OWNED BY "public"."savingbook"."bookid";



CREATE SEQUENCE IF NOT EXISTS "public"."trans_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."trans_seq" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."transaction" (
    "transactionid" character varying(20) DEFAULT ("to_char"("now"(), 'YYYYMMDDHH24MISS'::"text") || "lpad"(("nextval"('"public"."trans_seq"'::"regclass"))::"text", 4, '0'::"text")) NOT NULL,
    "bookid" integer,
    "transactiontype" character varying(12),
    "amount" numeric(15,2),
    "transactiondate" timestamp with time zone DEFAULT "now"(),
    "note" "text",
    "tellerid" integer,
    CONSTRAINT "check_transactiontype" CHECK ((("transactiontype")::"text" = ANY ((ARRAY['Deposit'::character varying, 'WithDraw'::character varying])::"text"[]))),
    CONSTRAINT "transaction_amount_check" CHECK (("amount" > (0)::numeric))
);


ALTER TABLE "public"."transaction" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."typesaving" (
    "typeid" integer NOT NULL,
    "termperiod" integer,
    "interest" numeric(8,3),
    "typename" character varying(20),
    "minimumdeposit" integer,
    "minimumbalance" integer DEFAULT 100000,
    "minimumterm" integer DEFAULT 15,
    "isactive" boolean DEFAULT true NOT NULL,
    CONSTRAINT "check_interest" CHECK ((("interest" >= (0)::numeric) AND ("interest" < (1)::numeric))),
    CONSTRAINT "check_termperiod" CHECK (("termperiod" >= 0)),
    CONSTRAINT "typesaving_minimumbalance_check" CHECK (("minimumbalance" > 0)),
    CONSTRAINT "typesaving_minimumdeposit_check" CHECK (("minimumdeposit" >= 0)),
    CONSTRAINT "typesaving_minimumterm_check" CHECK (("minimumterm" >= 0))
);


ALTER TABLE "public"."typesaving" OWNER TO "postgres";


COMMENT ON COLUMN "public"."typesaving"."minimumbalance" IS 'Là số tiền tối thiểu để mở sổ/duy trì sổ';



COMMENT ON COLUMN "public"."typesaving"."minimumterm" IS '(Đơn vị: Ngày) Thời gian gửi tối thiểu; Không thể rút tiền khi thời gian mở sổ bé hơn';



COMMENT ON COLUMN "public"."typesaving"."isactive" IS 'loại sổ có đang hoạt động ?';



CREATE SEQUENCE IF NOT EXISTS "public"."typesaving_typeid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."typesaving_typeid_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."typesaving_typeid_seq" OWNED BY "public"."typesaving"."typeid";



CREATE TABLE IF NOT EXISTS "public"."useraccount" (
    "userid" integer NOT NULL,
    "password" character varying(100) NOT NULL,
    "accountstatus" character varying(20),
    CONSTRAINT "check_accountstatus" CHECK ((("accountstatus")::"text" = ANY ((ARRAY['Unsubmitted'::character varying, 'Submitted'::character varying, 'Approved'::character varying, 'Rejected'::character varying, 'Active'::character varying, 'Disable'::character varying])::"text"[])))
);


ALTER TABLE "public"."useraccount" OWNER TO "postgres";


ALTER TABLE ONLY "public"."customer" ALTER COLUMN "customerid" SET DEFAULT "nextval"('"public"."customer_customerid_seq"'::"regclass");



ALTER TABLE ONLY "public"."role" ALTER COLUMN "roleid" SET DEFAULT "nextval"('"public"."role_roleid_seq"'::"regclass");



ALTER TABLE ONLY "public"."savingbook" ALTER COLUMN "bookid" SET DEFAULT "nextval"('"public"."savingbook_bookid_seq"'::"regclass");



ALTER TABLE ONLY "public"."typesaving" ALTER COLUMN "typeid" SET DEFAULT "nextval"('"public"."typesaving_typeid_seq"'::"regclass");



ALTER TABLE ONLY "public"."branch"
    ADD CONSTRAINT "branch_pkey" PRIMARY KEY ("branchid");



ALTER TABLE ONLY "public"."customer"
    ADD CONSTRAINT "customer_citizenid_key" UNIQUE ("citizenid");



ALTER TABLE ONLY "public"."customer"
    ADD CONSTRAINT "customer_pkey" PRIMARY KEY ("customerid");



ALTER TABLE ONLY "public"."empcounter"
    ADD CONSTRAINT "empcounter_pkey" PRIMARY KEY ("branchid", "roleid");



ALTER TABLE ONLY "public"."employee"
    ADD CONSTRAINT "employee_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."employee"
    ADD CONSTRAINT "employee_pkey" PRIMARY KEY ("employeeid");



ALTER TABLE ONLY "public"."role"
    ADD CONSTRAINT "role_pkey" PRIMARY KEY ("roleid");



ALTER TABLE ONLY "public"."savingbook"
    ADD CONSTRAINT "savingbook_pkey" PRIMARY KEY ("bookid");



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "transaction_pkey" PRIMARY KEY ("transactionid");



ALTER TABLE ONLY "public"."typesaving"
    ADD CONSTRAINT "typesaving_pkey" PRIMARY KEY ("typeid");



ALTER TABLE ONLY "public"."useraccount"
    ADD CONSTRAINT "useraccount_pkey" PRIMARY KEY ("userid");



CREATE OR REPLACE TRIGGER "employee_create_useraccount" AFTER INSERT ON "public"."employee" FOR EACH ROW EXECUTE FUNCTION "public"."create_useraccount_after_employee"();



CREATE OR REPLACE TRIGGER "employee_id_trigger" BEFORE INSERT ON "public"."employee" FOR EACH ROW WHEN (("new"."employeeid" IS NULL)) EXECUTE FUNCTION "public"."gen_employee_id_v2"();



CREATE OR REPLACE TRIGGER "maturity_date_set" BEFORE INSERT ON "public"."savingbook" FOR EACH ROW EXECUTE FUNCTION "public"."maturity_date_setting"();



CREATE OR REPLACE TRIGGER "status_is_close_closetime" BEFORE UPDATE ON "public"."savingbook" FOR EACH ROW EXECUTE FUNCTION "public"."status_close_closetime"();



CREATE OR REPLACE TRIGGER "status_is_open_closetime" BEFORE UPDATE ON "public"."savingbook" FOR EACH ROW EXECUTE FUNCTION "public"."status_open_closetime"();



CREATE OR REPLACE TRIGGER "user_delete_cascade_employee" AFTER DELETE ON "public"."useraccount" FOR EACH ROW EXECUTE FUNCTION "public"."delete_employee_after_account"();



ALTER TABLE ONLY "public"."empcounter"
    ADD CONSTRAINT "empcounter_branchid_fkey" FOREIGN KEY ("branchid") REFERENCES "public"."branch"("branchid");



ALTER TABLE ONLY "public"."empcounter"
    ADD CONSTRAINT "empcounter_roleid_fkey" FOREIGN KEY ("roleid") REFERENCES "public"."role"("roleid");



ALTER TABLE ONLY "public"."employee"
    ADD CONSTRAINT "employee_branchid_fkey" FOREIGN KEY ("branchid") REFERENCES "public"."branch"("branchid");



ALTER TABLE ONLY "public"."employee"
    ADD CONSTRAINT "employee_roleid_fkey" FOREIGN KEY ("roleid") REFERENCES "public"."role"("roleid");



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "fk_bookidtransaction_savingbook" FOREIGN KEY ("bookid") REFERENCES "public"."savingbook"("bookid");



ALTER TABLE ONLY "public"."savingbook"
    ADD CONSTRAINT "fk_customeridsavingbook_customer" FOREIGN KEY ("customerid") REFERENCES "public"."customer"("customerid");



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "fk_tellerid_transaction_useraccount" FOREIGN KEY ("tellerid") REFERENCES "public"."useraccount"("userid");



ALTER TABLE ONLY "public"."savingbook"
    ADD CONSTRAINT "fk_typeidsavingbook_typesaving" FOREIGN KEY ("typeid") REFERENCES "public"."typesaving"("typeid");



ALTER TABLE ONLY "public"."useraccount"
    ADD CONSTRAINT "useraccount_userid_fkey" FOREIGN KEY ("userid") REFERENCES "public"."employee"("employeeid");



CREATE POLICY "Enable read access for all users" ON "public"."useraccount" FOR SELECT USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."create_useraccount_after_employee"() TO "anon";
GRANT ALL ON FUNCTION "public"."create_useraccount_after_employee"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_useraccount_after_employee"() TO "service_role";



GRANT ALL ON FUNCTION "public"."delete_employee_after_account"() TO "anon";
GRANT ALL ON FUNCTION "public"."delete_employee_after_account"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_employee_after_account"() TO "service_role";



GRANT ALL ON FUNCTION "public"."gen_employee_id_v2"() TO "anon";
GRANT ALL ON FUNCTION "public"."gen_employee_id_v2"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."gen_employee_id_v2"() TO "service_role";



GRANT ALL ON FUNCTION "public"."generate_employee_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."generate_employee_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_employee_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."maturity_date_setting"() TO "anon";
GRANT ALL ON FUNCTION "public"."maturity_date_setting"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."maturity_date_setting"() TO "service_role";



GRANT ALL ON FUNCTION "public"."status_close_closetime"() TO "anon";
GRANT ALL ON FUNCTION "public"."status_close_closetime"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."status_close_closetime"() TO "service_role";



GRANT ALL ON FUNCTION "public"."status_open_closetime"() TO "anon";
GRANT ALL ON FUNCTION "public"."status_open_closetime"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."status_open_closetime"() TO "service_role";


















GRANT ALL ON TABLE "public"."branch" TO "anon";
GRANT ALL ON TABLE "public"."branch" TO "authenticated";
GRANT ALL ON TABLE "public"."branch" TO "service_role";



GRANT ALL ON SEQUENCE "public"."branch_branchid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."branch_branchid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."branch_branchid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customer" TO "anon";
GRANT ALL ON TABLE "public"."customer" TO "authenticated";
GRANT ALL ON TABLE "public"."customer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customer_customerid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customer_customerid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customer_customerid_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."emp_suffix_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."emp_suffix_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."emp_suffix_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empcounter" TO "anon";
GRANT ALL ON TABLE "public"."empcounter" TO "authenticated";
GRANT ALL ON TABLE "public"."empcounter" TO "service_role";



GRANT ALL ON TABLE "public"."employee" TO "anon";
GRANT ALL ON TABLE "public"."employee" TO "authenticated";
GRANT ALL ON TABLE "public"."employee" TO "service_role";



GRANT ALL ON TABLE "public"."role" TO "anon";
GRANT ALL ON TABLE "public"."role" TO "authenticated";
GRANT ALL ON TABLE "public"."role" TO "service_role";



GRANT ALL ON SEQUENCE "public"."role_roleid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."role_roleid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."role_roleid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."savingbook" TO "anon";
GRANT ALL ON TABLE "public"."savingbook" TO "authenticated";
GRANT ALL ON TABLE "public"."savingbook" TO "service_role";



GRANT ALL ON SEQUENCE "public"."savingbook_bookid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."savingbook_bookid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."savingbook_bookid_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."trans_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trans_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trans_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transaction" TO "anon";
GRANT ALL ON TABLE "public"."transaction" TO "authenticated";
GRANT ALL ON TABLE "public"."transaction" TO "service_role";



GRANT ALL ON TABLE "public"."typesaving" TO "anon";
GRANT ALL ON TABLE "public"."typesaving" TO "authenticated";
GRANT ALL ON TABLE "public"."typesaving" TO "service_role";



GRANT ALL ON SEQUENCE "public"."typesaving_typeid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."typesaving_typeid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."typesaving_typeid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."useraccount" TO "anon";
GRANT ALL ON TABLE "public"."useraccount" TO "authenticated";
GRANT ALL ON TABLE "public"."useraccount" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

alter table "public"."savingbook" drop constraint "check_status";

alter table "public"."transaction" drop constraint "check_transactiontype";

alter table "public"."useraccount" drop constraint "check_accountstatus";

alter table "public"."savingbook" add constraint "check_status" CHECK (((status)::text = ANY ((ARRAY['Open'::character varying, 'Close'::character varying])::text[]))) not valid;

alter table "public"."savingbook" validate constraint "check_status";

alter table "public"."transaction" add constraint "check_transactiontype" CHECK (((transactiontype)::text = ANY ((ARRAY['Deposit'::character varying, 'WithDraw'::character varying])::text[]))) not valid;

alter table "public"."transaction" validate constraint "check_transactiontype";

alter table "public"."useraccount" add constraint "check_accountstatus" CHECK (((accountstatus)::text = ANY ((ARRAY['Unsubmitted'::character varying, 'Submitted'::character varying, 'Approved'::character varying, 'Rejected'::character varying, 'Active'::character varying, 'Disable'::character varying])::text[]))) not valid;

alter table "public"."useraccount" validate constraint "check_accountstatus";


